/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/scim2/Users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List users
     * @description Gets details for all the users.
     */
    get: operations['listUsers'];
    put?: never;
    /**
     * Create a user
     * @description Creates a new user.
     */
    post: operations['createUser'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scim2/Users/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the user. */
        id: string;
      };
      cookie?: never;
    };
    /**
     * Get a user
     * @description Gets the specified user.
     */
    get: operations['getUser'];
    /**
     * Update a user
     * @description Updates the user that matches the supplied id.
     */
    put: operations['updateUser'];
    post?: never;
    /**
     * Delete a user
     * @description Deletes the user that matches the supplied id.
     */
    delete: operations['deleteUser'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/scim2/Me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the current user
     * @description Gets the user from the jwt token provided.
     */
    get: operations['getSelf'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/capabilities': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the caller's capabilities
     * @description Reports what the calling identity is allowed to do, for callers that cannot
     *     infer it from other read endpoints. Metastore ownership in particular is not
     *     exposed anywhere else, which otherwise forces a UI to guess whether an admin
     *     may perform an action.
     */
    get: operations['getSelfCapabilities'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Start the server-hosted login flow
     * @description Redirects the browser to the configured identity provider's authorization endpoint
     *     (server.authorization-url) with a one-time state bound to a short-lived cookie. The
     *     identity provider sends the browser back to /auth/callback. Only available when the
     *     OAuth client properties are configured on the server; the client secret never leaves it.
     */
    get: operations['login'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Complete the server-hosted login flow
     * @description Receives the authorization code from the identity provider, exchanges it for an identity
     *     token using the server-held client secret, verifies that token exactly like the token
     *     exchange endpoint does, and issues a Unity Catalog access token as the UC_TOKEN cookie
     *     before redirecting back into the UI.
     */
    get: operations['loginCallback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Which sign-in methods this server offers
     * @description Public (no token required). Lets a UI decide at runtime whether sign-in is required at all
     *     and which entry points to show, so one UI build follows the server's configuration instead
     *     of baking the choice in.
     */
    get: operations['getAuthProviders'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/admin/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign in as the built-in administrator with a password
     * @description Exchanges the administrator password configured on the server (server.admin-password) for
     *     a Unity Catalog access token, returned in the body and set as the UC_TOKEN cookie. Serves
     *     the UI's administrator entry point; unavailable unless the password is configured.
     */
    post: operations['adminLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/token/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Open a browser session with an access token already held
     * @description Accepts a Unity Catalog access token issued by this server (the one in etc/conf/token.txt,
     *     for instance) and sets it as the UC_TOKEN cookie, so an operator can reach the UI with the
     *     token instead of a password. The token is verified as any request's token is -- signature,
     *     expiry and an enabled user -- and is handed back unchanged, so the session cannot outlive
     *     it. Tokens from an identity provider go to /auth/tokens instead.
     */
    post: operations['tokenLogin'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Get a token using an OAuth2 flow
     * @description Exchanges credentials for a token using the OAuth2 token exchange.
     */
    post: operations['getToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke access token cookie
     * @description Revokes the access token cookie.
     */
    post: operations['logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    User: {
      /** @description The unique identifier of the user. */
      id: string;
      /** @description The name of the user. */
      name: string;
      /** @description The email address of the user. */
      email: string;
      /** @description The external identifier of the user. */
      external_id?: string;
      /**
       * @description The state of the account.
       * @enum {string}
       */
      state?: UserState;
      /** @description The URL of the user's profile picture. */
      picture_url?: string;
      /**
       * Format: int64
       * @description The time the user was created.
       */
      created_at?: number;
      /**
       * Format: int64
       * @description The time the user was last updated.
       */
      updated_at?: number;
    };
    /** @description List of SCIM User resources. */
    UserResourceList: {
      /**
       * Format: int32
       * @description The total number of results.
       */
      totalResults?: number;
      /**
       * Format: int32
       * @description The number of items per page.
       */
      itemsPerPage?: number;
      /**
       * Format: int32
       * @description The index of the first result.
       */
      startIndex?: number;
      /** @description The list of User resources. */
      Resources?: components['schemas']['UserResource'][];
      /** @description User list id metadata. */
      id?: string;
      /** @description User list external id metadata. */
      externalId?: string;
      /** @description The metadata of the user. */
      meta?: {
        resourceType?: string;
        created?: string;
        lastModified?: string;
      };
    };
    AuthProviders: {
      /** @description Whether requests must carry a token at all (server.authorization). */
      authorization_enabled?: boolean;
      /** @description Whether the server-hosted OAuth sign-in (/auth/login) is configured. */
      hosted_login?: boolean;
      /** @description Whether the administrator password sign-in (/auth/admin/login) is configured. */
      admin_login?: boolean;
    };
    SelfCapabilities: {
      /**
       * @description Whether the caller owns the metastore. Metastore owners are authorized for
       *     every securable, including ones they do not personally own.
       */
      metastore_admin?: boolean;
    };
    /** @description SCIM provides a resource type for "User" resources. */
    UserResource: {
      /** @description The id of the user. */
      id?: string;
      /** @description The name of the user. */
      displayName?: string;
      /** @description The SCIM external id. */
      externalId?: string;
      /** @description E-mail addresses for the user. */
      emails?: components['schemas']['Email'][];
      /** @description The active status of the user. */
      active?: boolean;
      /** @description The metadata of the user. */
      meta?: {
        created?: string;
        lastModified?: string;
      };
      /** @description The photos of the user. */
      photos?: {
        /** @description The url of the user's photo. */
        value?: string;
      }[];
    };
    /** @description SCIM email for a user. */
    Email: {
      /** @description The email of the user. */
      value?: string;
      /** @description If the email is primary. */
      primary?: boolean;
    };
    /**
     * @description Grant type identifier, from RFC 8693 Section 2.
     *     See https://datatracker.ietf.org/doc/html/rfc8693#section-2
     * @enum {string}
     */
    GrantType: GrantType;
    /**
     * @description Token type identifier, from RFC 8693 Section 3.
     *     See https://datatracker.ietf.org/doc/html/rfc8693#section-3
     * @enum {string}
     */
    TokenType: TokenType;
    /**
     * @description Access token type identifier, from RFC 8693 Section 2.
     *     See https://datatracker.ietf.org/doc/html/rfc8693#section-2
     * @enum {string}
     */
    AccessTokenType: AccessTokenType;
    /**
     * @description Authorization endpoint response type, from RFC 6749 Section 3.
     *     See https://datatracker.ietf.org/doc/html/rfc6749#section-3
     * @enum {string}
     */
    ResponseType: ResponseType;
    /**
     * @description Authorization grant type, from RFC 6749 Section 4.
     *     See https://datatracker.ietf.org/doc/html/rfc6749#section-4
     * @enum {string}
     */
    AuthorizationGrantType: AuthorizationGrantType;
    /**
     * @description The /auth/tokens endpoint supports an extension type.
     *     If ext=cookie is specified in the request query, the server will store a token in the user agent's cookie.
     * @enum {string}
     */
    TokenEndpointExtensionType: TokenEndpointExtensionType;
    /**
     * @description OAuth2 token exchange request form.
     *     See https://datatracker.ietf.org/doc/html/rfc8693
     */
    OAuthTokenExchangeForm: {
      grant_type: components['schemas']['GrantType'];
      /** @description The authorization scope for the token exchange request. */
      scope?: string;
      requested_token_type?: components['schemas']['TokenType'];
      /** @description The security token that represents the identity of the party on behalf of whom the request is being made. */
      subject_token: string;
      subject_token_type: components['schemas']['TokenType'];
      /** @description The security token that represents the identity of the acting party. */
      actor_token?: string;
      actor_token_type?: components['schemas']['TokenType'];
    };
    /**
     * @description OAuth2 token exchange response.
     *     See https://datatracker.ietf.org/doc/html/rfc8693
     */
    OAuthTokenExchangeInfo: {
      /** @description The access token for the token exchange request. */
      access_token: string;
      issued_token_type: components['schemas']['TokenType'];
      token_type: components['schemas']['AccessTokenType'];
      /**
       * Format: int64
       * @description The lifetime of the access token in seconds for the token exchange.
       */
      expires_in?: number;
      /** @description The authorization scope for the token exchange. */
      scope?: string;
      /** @description The refresh token for the token exchange. */
      refresh_token?: string;
    };
    /**
     * @description OAuth2 authorization request form.
     *     See https://datatracker.ietf.org/doc/html/rfc6749
     */
    OAuthAuthorizationForm: {
      response_type: components['schemas']['ResponseType'];
      /** @description The client identifier that represents the registration information provided by the client */
      client_id: string;
      /** @description The URI that authorization server directs the resource owner's user-agent back to the client. */
      redirect_uri?: string;
      /** @description The scope of the access request. */
      scope?: string;
      /** @description An opaque value used by the client to maintain state between the request and callback. */
      state?: string;
    };
    /**
     * @description OAuth2 authorization request.
     *     See https://datatracker.ietf.org/doc/html/rfc6749
     */
    OAuthAuthorizationInfo: {
      /** @description The authorization code generated by the authorization server. */
      code: string;
      /** @description An opaque value used by the client to maintain state between the request and callback. */
      state?: string;
    };
    /**
     * @description OAuth2 access token request.
     *     See https://datatracker.ietf.org/doc/html/rfc6749
     */
    OAuthAccessTokenForm: {
      grant_type: components['schemas']['AuthorizationGrantType'];
      /** @description The authorization code received from the authorization server. */
      code: string;
      /** @description The URI that authorization server directs the resource owner's user-agent back to the client. */
      redirect_uri?: string;
      /** @description The client identifier that represents the registration information provided by the client */
      client_id?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listUsers: {
    parameters: {
      query?: {
        /** @description Query by which the results have to be filtered. */
        filter?: string;
        /** @description Specifies the index of the first result. First item is number 1. */
        startIndex?: number;
        /** @description Desired number of results per page. If no count is provided, it defaults to 50. */
        count?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user list was successfully retrieved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/scim+json': components['schemas']['UserResourceList'];
        };
      };
    };
  };
  createUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UserResource'];
      };
    };
    responses: {
      /** @description The new user was successfully created. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/scim+json': components['schemas']['UserResource'];
        };
      };
    };
  };
  getUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the user. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user was successfully retrieved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/scim+json': components['schemas']['UserResource'];
        };
      };
    };
  };
  updateUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the user. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['UserResource'];
      };
    };
    responses: {
      /** @description The user was successfully updated. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/scim+json': components['schemas']['UserResource'];
        };
      };
    };
  };
  deleteUser: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description The id of the user. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user was successfully deleted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/scim+json': unknown;
        };
      };
    };
  };
  getSelf: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The user was successfully retrieved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResource'];
        };
      };
    };
  };
  getSelfCapabilities: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The capabilities were successfully retrieved. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SelfCapabilities'];
        };
      };
    };
  };
  login: {
    parameters: {
      query?: {
        /** @description Path within the UI to return to after login. Must be a relative path. */
        redirect?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to the identity provider. */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The hosted login flow is not configured on this server. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  loginCallback: {
    parameters: {
      query?: {
        code?: string;
        state?: string;
        error?: string;
        error_description?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Login succeeded; the UC_TOKEN cookie is set and the browser is sent back to the UI. */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or mismatched state, an error reported by the identity provider, or an unknown user. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAuthProviders: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The available sign-in methods. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthProviders'];
        };
      };
    };
  };
  adminLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': {
          username: string;
          /** Format: password */
          password: string;
        };
      };
    };
    responses: {
      /** @description Signed in; the UC_TOKEN cookie is set. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OAuthTokenExchangeInfo'];
        };
      };
      /** @description Administrator login is not configured on this server. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Wrong username or password. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  tokenLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': {
          /** Format: password */
          token: string;
        };
      };
    };
    responses: {
      /** @description Signed in; the UC_TOKEN cookie is set. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OAuthTokenExchangeInfo'];
        };
      };
      /** @description No token supplied. */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description The token is not valid for sign-in. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getToken: {
    parameters: {
      query?: {
        /** @description Specifies whether the server will store a token in the user agent's cookie. */
        ext?: components['schemas']['TokenEndpointExtensionType'];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': {
          grant_type: components['schemas']['GrantType'];
          /** @description The authorization scope for the token exchange request. */
          scope?: string;
          requested_token_type?: components['schemas']['TokenType'];
          /** @description The security token that represents the identity of the party on behalf of whom the request is being made. */
          subject_token: string;
          subject_token_type: components['schemas']['TokenType'];
          /** @description The security token that represents the identity of the acting party. */
          actor_token?: string;
          actor_token_type?: components['schemas']['TokenType'];
        };
      };
    };
    responses: {
      /** @description The token exchange was successfully granted. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OAuthTokenExchangeInfo'];
        };
      };
    };
  };
  logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': Record<string, never> | null;
      };
    };
    responses: {
      /** @description The access token will be revoked. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
export enum UserState {
  ENABLED = 'ENABLED',
  DISABLED = 'DISABLED',
}
export enum GrantType {
  TOKEN_EXCHANGE = 'urn:ietf:params:oauth:grant-type:token-exchange',
}
export enum TokenType {
  ACCESS_TOKEN = 'urn:ietf:params:oauth:token-type:access_token',
  REFRESH_TOKEN = 'urn:ietf:params:oauth:token-type:refresh_token',
  ID_TOKEN = 'urn:ietf:params:oauth:token-type:id_token',
  SAML1 = 'urn:ietf:params:oauth:token-type:saml1',
  SAML2 = 'urn:ietf:params:oauth:token-type:saml2',
  JWT = 'urn:ietf:params:oauth:token-type:jwt',
}
export enum AccessTokenType {
  Bearer = 'Bearer',
}
export enum ResponseType {
  code = 'code',
  token = 'token',
}
export enum AuthorizationGrantType {
  authorization_code = 'authorization_code',
}
export enum TokenEndpointExtensionType {
  cookie = 'cookie',
}
