# Dependency licences can only change when the build definition changes, so this
# runs on the build files rather than on every pull request. It used to be a step
# inside the unit test matrix, where it cost ~4.5 minutes per leg on every change.

name: License Check

on:
  push:
    branches: [ "main", "branch-*" ]
    paths:
      - build.sbt
      - version.sbt
      - project/**
      - .github/workflows/license-check.yml
  pull_request:
    branches: [ "main", "branch-*" ]
    paths:
      - build.sbt
      - version.sbt
      - project/**
      - .github/workflows/license-check.yml

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  license-check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - name: Set up JDK 17
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
      with:
        java-version: '17'
        distribution: 'temurin'
        # Caches ~/.sbt, ~/.ivy2/cache and ~/.cache/coursier.
        cache: 'sbt'

    - name: Cache the sbt launcher
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: build/sbt-launch-*.jar
        key: sbt-launcher-${{ hashFiles('project/build.properties') }}

    - name: Run license check
      run: build/sbt licenseCheck
